name: stale
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-issue-message: "Issues have been closed after 60 days of inactivity. It’s been at least 20 days since the last update."
          stale-pr-message: "Pull requests are closed after 60 days of inactivity. It’s been at least 20 days since the last update here."
          exempt-issue-label: not stale
          exempt-pr-label: not stale
